WebApplication1/Controllers/AutenticacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.ViewModels;
using WebApplication1.Utils;
using System.Security.Claims;

namespace WebApplication1.Controllers  {
    public class AutenticacaoController : Controller {

        private UsuariosContext db = new UsuariosContext();

        //public string UrlRetorno { get; private set; }

        public ActionResult Cadastrar() { return View(); }

        [HttpPost]
        public ActionResult Cadastrar(CadastroUsuarioViewModel viewModel) {

            if (!ModelState.IsValid) {
                return View(viewModel);
            }

            if (db.Usuario.Count(u => u.Login == viewModel.Login) > 0) {
                ModelState.AddModelError("Login", "Esse Login já esta em uso");
                return View(viewModel);
            }

            Usuario novoUsuario = new Usuario {
                Nome = viewModel.Nome,
                Login = viewModel.Login,
                Senha = Hash.GeraHash(viewModel.Senha)

            };


            db.Usuario.Add(novoUsuario);
            db.SaveChanges();
            TempData["Mensagem"] = "Cadastro Realizado com sucesso";
            return View();

        }


        public ActionResult Login(String ReturnUrl) {
            var viewmodel = new LoginViewModel{
               UrlRetorno = ReturnUrl
            };
            return View(viewmodel);
        }


        [HttpPost]
        public ActionResult Login(LoginViewModel viewmodel){

            if (!ModelState.IsValid) { return View(viewmodel); }

            var usuario = db.Usuario.FirstOrDefault( u => u.Login == viewmodel.Login);

            if (usuario == null){
                ModelState.AddModelError("Senha", "Login ou senha incorreta");
                return View(viewmodel);
            }
            if (usuario.Senha != Hash.GeraHash(viewmodel.Senha))  {
                ModelState.AddModelError("Senha", "Login ou senha incorreta");
                return View(viewmodel);
            }


            var Identidade = new ClaimsIdentity(new[]{//cookie de credenciais
                new Claim(ClaimTypes.Name, usuario.Nome),
                new Claim("Login", usuario.Login)
              }, "ApplicationCookie");

            Request.GetOwinContext().Authentication.SignIn(Identidade);
            if ((!String.IsNullOrWhiteSpace(viewmodel.UrlRetorno)) || (Url.IsLocalUrl(viewmodel.UrlRetorno)))
            {
                return Redirect(viewmodel.UrlRetorno);
            }
            else return RedirectToAction("Index", "Painel");
        }

       public ActionResult Logout() {
            Request.GetOwinContext().Authentication.SignOut("ApplicationCookie");
            return RedirectToAction("Index","Home");
        }
    }
}

WebApplication1/Controllers/EspecialidadesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace CadeMedico.Controllers {
    public class EspecialidadesController : Controller
    {
        private UsuariosContext db = new UsuariosContext();

        // GET: Especialidades
        public ActionResult Index(){
            return View(db.Especialidades.ToList());
        }

        // GET: Especialidades/Create
        [Authorize]
        public ActionResult Create(){
            return View();
        }

        // POST: Especialidades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "EspecialidadeID,Nome")] Especialidade especialidade)
        {
            if (ModelState.IsValid)
            {
                db.Especialidades.Add(especialidade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(especialidade);
        }

        // GET: Especialidades/Edit/5
        [Authorize]
        public ActionResult Edit(int? id) {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Especialidade especialidade = db.Especialidades.Find(id);
            if (especialidade == null)
            {
                return HttpNotFound();
            }
            return View(especialidade);
        }

        // POST: Especialidades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "EspecialidadeID,Nome")] Especialidade especialidade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(especialidade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(especialidade);
        }

        // GET: Especialidades/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Especialidade especialidade = db.Especialidades.Find(id);
            if (especialidade == null)
            {
                return HttpNotFound();
            }
            return View(especialidade);
        }

        // POST: Especialidades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Especialidade especialidade = db.Especialidades.Find(id);
            db.Especialidades.Remove(especialidade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

WebApplication1/Controllers/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Utils;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class PerfilController : Controller
    {
        private UsuariosContext db = new UsuariosContext();
        
        [Authorize]
        // GET: Perfil
        public ActionResult AlterarSenha() {
            return View();
        }


        [Authorize]
        [HttpPost]
        public ActionResult AlterarSenha(AlterarSenhaViewModel viewmodel){

            if (!ModelState.IsValid)
            {
                return View();
            }
            var Identidade = User.Identity as ClaimsIdentity;

            //var Login  = db.identity.Claims.FirstOrDefault(u => u.login == login);

            var Login = Identidade.Claims.FirstOrDefault(
                  c => c.Type == "Login").Value;

            var usuario = db.Usuario.FirstOrDefault(
                u => u.Login == Login);

        if(Hash.GeraHash(viewmodel.SenhaAtual) != (usuario.Senha)){
                ModelState.AddModelError("SenhaAtual","Senha Incorreta");
                return View();
         }

            usuario.Senha = Hash.GeraHash(viewmodel.NovaSenha);
            db.Entry(usuario).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index", "Painel");
            

        }

    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">

                    <li>@Html.ActionLink("Medicos", "Index", "Medicos")</li>
                    <li>@Html.ActionLink("Cidades", "Index", "Cidades")</li>
                    <li>@Html.ActionLink("Especialidade", "Index", "Especialidades")</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @User.Identity.Name<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Sair", "Logout", "Autenticacao")</li>
                                <li>@Html.ActionLink("Alterar Senha", "AlterarSenha", "Perfil")</li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Autenticacao")</li>
                        <li>@Html.ActionLink("Cadastre-se", "Cadastrar", "Autenticacao")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                &copy; @DateTime.Now.Year - Luiz Eduardo de O Martins <i class="fa fa-copyright" aria-hidden="true"></i>
            </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js" integrity="sha256-jDnOKIOq2KNsQZTcBTEnsp76FnfMEttF6AV2DF2fFNE=" crossorigin="anonymous"></script>
    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>